-- Import all products - Run in phpMyAdmin
SET NAMES utf8mb4;

-- Tắt kiểm tra foreign key
SET FOREIGN_KEY_CHECKS = 0;

-- Xóa dữ liệu liên quan trước
DELETE FROM ChiTietDonHang;
DELETE FROM GioHang;
DELETE FROM SanPham;

-- Reset AUTO_INCREMENT
ALTER TABLE SanPham AUTO_INCREMENT = 1;
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00012', 'Mì Thập Cẩm No Nê (Kim Chi/ Soyum/ Sincay)', 'Mì cay Sasin, thịt heo, tôm, cá viên, trứng ngâm tương, thanh cua, chả cá Hàn Quốc, kim chi, nấm, súp lơ, bắp cải tím, ngò gai', 77000, 1, 'MenuItem_M00012.webp', 1, 1, 3, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('MI0008', 'Mì Thập Cẩm (Kim chi/ Soyum/ Sincay)', 'Mì cay Sasin, Thịt bò, tôm, mực, chả cá Hàn Quốc, cá viên, kim chi, súp lơ, nấm, bắp cải tím, ngò gai', 69000, 1, 'MenuItem_MI0008.webp', 1, 1, 3, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00018', 'Mì Hải Sản (Kim chi/ Soyum/ Sincay)', 'Mì cay Sasin, tôm, mực, chả cá Hàn Quốc, cá viên, kim chi, súp lơ, ngò gai, nấm, bắp cải tím.', 62000, 1, 'MenuItem_M00018.webp', 1, 1, 3, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('MI0005', 'Mì Hải Sản Thanh Cua (Kim chi/ Soyum/ Sincay)', 'Mì cay Sasin, Tôm, thanh cua, chả cá Hàn Quốc, cá viên, kim chi, súp lơ, nấm, bắp cải tím, ngò gai', 62000, 1, 'MenuItem_MI0005.webp', 1, 0, 3, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00021', 'Mì Bò Mỹ (Kim chi/ Soyum/ Sincay)', 'Mì cay Sasin, thịt bò, xúc xích, cá viên, kim chi, súp lơ, nấm, bắp cải tím, ngò gai', 59000, 1, 'MenuItem_M00021.webp', 1, 0, 3, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00022', 'Mì Bò Trứng (Kim chi/ Soyum/ Sincay)', 'Mì cay Sasin, thịt bò, trứng lòng đào, xúc xích, cá viên, kim chi, súp lơ, nấm, bắp cải tím, ngò gai', 65000, 1, 'MenuItem_M00022.webp', 1, 0, 3, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00109', 'Mì Đùi Gà (Kim chi/ Soyum/ Sincay)', 'Mì cay Sasin, đùi gà, cá viên, kim chi, súp lơ, nấm, bắp cải tím, ngò gai, chả cá Hàn Quốc', 59000, 1, 'MenuItem_M00109.webp', 1, 0, 3, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('MI0004', 'Mì Kim Chi Cá', 'Mì cay Sasin, phi lê cá, nấm, cá viên, kim chi, súp lơ, bắp cải tím, ngò gai', 49000, 1, 'MenuItem_MI0004.webp', 1, 0, 3, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00027', 'Mì Kim Chi Gogi', 'Mì cay Sasin, thịt heo, xúc xích, kim chi, cá viên, kim chi, súp lơ, nấm, bắp cải tím, ngò gai', 49000, 1, 'MenuItem_M00027.webp', 1, 0, 3, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00011', 'Mì Kim Chi Xúc Xích Cá Viên', 'Mì cay Sasin, xúc xích, kim chi, nấm, cá viên, súp lơ, bắp cải tím, chả cá Hàn Quốc, ngò gai', 39000, 1, 'MenuItem_M00011.webp', 1, 0, 3, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00015', 'Mì Trộn Tương Đen Heo Cuộn', 'Mì cay Sasin, heo cuộn, cá viên, cà rốt, ớt chuông, hành tây, hành baro', 69000, 2, 'MenuItem_M00015.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00016', 'Mì Trộn Tương Đen Bò Mỹ', 'Mì cay Sasin, thịt bò, cá viên, chả cá Hàn Quốc, hành tây, ớt chuông, cà rốt, hành baro, mè', 65000, 2, 'MenuItem_M00016.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00014', 'Mì Trộn Tương Đen Gà', 'Mì cay Sasin, gà, cá viên, hành tây, ớt chuông, cà rốt, hành baro, mè', 59000, 2, 'MenuItem_M00014.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00013', 'Mì Trộn Tương Đen Mandu', 'Mì cay Sasin, mandu, cá viên, hành tây, ớt chuông, cà rốt, hành baro, mè', 55000, 2, 'MenuItem_M00013.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00130', 'Mì Xào Hải Sản', 'Mì cay Sasin, tôm, mực, chả cá HQ, cá viên, ớt chuông, hành tây, cải bó xôi, nấm, mè', 69000, 3, 'MenuItem_M00130.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00131', 'Mì Xào Sasin', 'Mì cay Sasin, thịt heo, xúc xích, cá viên, súp lơ, ớt chuông, hành tây, cải bó xôi, nấm', 65000, 3, 'MenuItem_M00131.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00132', 'Mì Trộn Xốt Phô Mai', 'Mì cay Sasin, gà, phô mai, xốt kem, cà rốt, hành baro', 62000, 3, 'MenuItem_M00132.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00129', 'Miến Trộn Ngũ Sắc Hàn Quốc', 'Miến, thịt bò, xúc xích, nấm, ớt chuông, cà rốt, hành tây, hành baro, cải bó xôi, chả cá HQ, mè', 65000, 4, 'MenuItem_M00129.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('MI0002', 'Mì Tương Hàn Mandu', 'Mì cay Sasin, manudu, xúc xích, súp lơ,cải thảo, nấm, hành baro', 52000, 4, 'MenuItem_MI0002.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('MI0001', 'Mì Tương Hàn Thịt Heo Cuộn', 'Mì cay Sasin, heo cuộn, cải thảo, trứng ngâm tương, súp lơ, nấm, hành baro', 65000, 4, 'MenuItem_MI0001.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00028', 'Cơm Trộn Thịt Bò Mỹ', 'Cơm, thịt bò, trứng, nấm, kim chi, rong biển, cà rốt, cải bó xôi, mè, ngò gai', 62000, 4, 'MenuItem_M00028.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00020', 'Cơm và Canh Kim Chi', 'Cơm, thịt heo, chả cá Hàn Quốc, cá viên, kim chi, nấm, súp lơ, ớt chuông, hành tây, ngò gai', 62000, 4, 'MenuItem_M00020.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('MI0003', 'Tokbok-cheese Bò Mỹ', 'Tokbokki, thịt bò, xúc xích, cá viên, phô mai, hành baro, mè', 62000, 4, 'MenuItem_MI0003.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('MI0006', 'Tokbokki Phô Mai Sasin', 'Tokbokki, xúc xích, chả cá Hàn Quốc, bắp cải, nấm, hành baro, phô mai', 59000, 4, 'MenuItem_MI0006.webp', 1, 1, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00030', 'Trứng Ngâm Tương', '마약 계란', 12000, 5, 'MenuItem_M00030.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00139', 'Bông Cải Xanh', '브로콜리', 15000, 5, 'MenuItem_M00139.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00034', 'Bắp Cải Tím', '적채', 15000, 5, 'MenuItem_M00034.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00113', 'Nấm Kim Châm Thêm', '에노키타케', 15000, 5, 'MenuItem_M00113.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00035', 'Mực', '오징어', 15000, 5, 'MenuItem_M00035.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00032', 'Tôm Thêm', '새우', 15000, 5, 'MenuItem_M00032.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00029', 'Thịt Heo Cuộn', '차슈', 15000, 5, 'MenuItem_M00029.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00033', 'Cá Viên Thêm', '어육 완자', 15000, 5, 'MenuItem_M00033.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00036', 'Xúc xích', '소시지', 15000, 5, 'MenuItem_M00036.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00138', 'Bắp Bò', '소사태', 19000, 5, 'MenuItem_M00138.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00031', 'Bò Thêm', '소고기', 19000, 5, 'MenuItem_M00031.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00140', 'Combo Xiên Que', '계피 꼬치 콤보', 12000, 5, 'MenuItem_M00140.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00112', 'Mì Nấu Thêm', '라면', 19000, 5, 'MenuItem_M00112.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00141', 'Combo Vui Vẻ (1 người)', '1 Món tự chọn, món áp dụng: Mì cá/ Mì đùi gà/ Mì gogi/ Mì xúc xích cá viên/ Mì bò Mỹ 1 Ly Coca-cola/ Sprite size L', 69000, 6, 'MenuItem_M00141.webp', 1, 1, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00142', 'Combo Gây Mê (1 người)', '1 Món tự chọn, món áp dụng: Miến xào/ Mì xào Sasin/ Mì xào hải sản/ Cơm và canh kim chi 1 Ly Coca-cola/ Sprite size L', 79000, 6, 'MenuItem_M00142.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00143', 'Combo Bạn Thân (2 người)', '2 Món tự chọn thuộc nhóm mì cay, không bao gồm mì thập cẩm no nê 1 phân khai vị tự. chọn: Bánh bạch tuộc/ Phô mai viên/ Khoai tây chiên/ Phô mai que/ Kimbap Sasin (6 cuộn)', 159000, 6, 'MenuItem_M00143.webp', 1, 1, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00144', 'Combo No Căng (2 người)', '2 Món tự chọn thuộc nhóm mì cay không bao gồm mì thập cẩm no nê 1 Tokbokki phô mai Sasin', 179000, 6, 'MenuItem_M00144.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00145', 'Combo Gia Đình (3 người)', '2 Món tự chọn thuộc nhóm mì cay, không bao gồm mì thập cẩm no nê. 1 Món bất kỳ trong nhóm: Mì tương đen/ Mì xào/ Món chính khác 1 Phần khai vị tự chọn: Bánh bạch tuộc/ Phô mai viên/ Khoai Tây Chiên/ P', 219000, 6, 'MenuItem_M00145.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00146', 'Combo Lẩu 2 Người', 'Lẩu (Hải sản/ Bò Mỹ) 1 Phần khai vị tự chọn: Bánh bạch tuộc/ Phô mai viên/ Khoai tây. chiên/ Phô mai que/ Kimbap Sasin (6 cuộn)', 225000, 6, 'MenuItem_M00146.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00117', 'Lẩu Sincay Hải Sản (2 Người)', 'Mì cay Sasin, thịt bò, bò viên, cá viên, chả cá Hàn Quốc, chả cá sợi, kim chi, nấm kim châm, súp lơ, bắp cải tím', 199000, 7, 'MenuItem_M00117.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00037', 'Lẩu Sincay Bò Mỹ (2 Người)', 'Mì cay Sasin, thịt bò, bò viên, cá viên, chả cá Hàn Quốc, chả cá sợi, kim chi, nấm kim châm, súp lơ, bắp cải tím.', 209000, 7, 'MenuItem_M00037.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00136', 'Lẩu Kim Chi Bò Mỹ (2 Người)', 'Mì cay Sasin, thịt bò, bò viên, cá viên, chả cá Hàn Quốc, chả cá sợi, kim chi, nấm kim châm, súp lơ, bắp cải tím', 209000, 7, 'MenuItem_M00136.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00038', 'Lẩu Kim Chi Hải Sản (2 Người)', 'Mì cay Sasin, tôm, mực, cá viên, kim chi, nấm kim châm, súp lơ, bắp cải tím', 209000, 7, 'MenuItem_M00038.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00116', 'Lẩu Soyum Hải Sản (2 Người)', 'Mì cay Sasin, tôm, mực, cá viên, kim chi, nấm kim châm, súp lơ, bắp cải tím', 209000, 7, 'MenuItem_M00116.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00119', 'Lẩu Soyum Bò Mỹ (2 Người)', 'Mì cay Sasin, thịt bò, bò viên, cá viên, chả cá Hàn Quốc, chả cá sợi, kim chi, nấm kim châm, súp lơ, bắp cải tím', 209000, 7, 'MenuItem_M00119.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00068', 'Trứng Gà (1 Quả)', '계란 1개', 9000, 8, 'MenuItem_M00068.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00065', 'Mì Gói', '라면', 12000, 8, 'MenuItem_M00065.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00060', 'Nấm Kim Châm Thêm', '에노키타케', 25000, 8, 'MenuItem_M00060.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00063', 'Cải Thảo', '배추', 25000, 8, 'MenuItem_M00063.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00062', 'Bông Cải Xanh', '브로콜리', 25000, 8, 'MenuItem_M00062.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00048', 'Bắp Cải Tím Thêm', '적채', 25000, 8, 'MenuItem_M00048.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00056', 'Cá Viên Thêm', '어육 완자', 25000, 8, 'MenuItem_M00056.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00049', 'Cá Thêm', '물고기', 25000, 8, 'MenuItem_M00049.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00057', 'Mực', '오징어', 25000, 8, 'MenuItem_M00057.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00052', 'Tôm Thêm', '새우', 25000, 8, 'MenuItem_M00052.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00066', 'Chả Cá Hàn Quốc', '어묵', 25000, 8, 'MenuItem_M00066.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00058', 'Xúc Xích Thêm', '소시지', 25000, 8, 'MenuItem_M00058.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00053', 'Thanh Cua', '게맛살', 25000, 8, 'MenuItem_M00053.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00137', 'Bắp Bò', '소사태', 25000, 8, 'MenuItem_M00137.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00054', 'Bò Thêm', '소고기', 25000, 8, 'MenuItem_M00054.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00059', 'Mandu', '만두', 25000, 8, 'MenuItem_M00059.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00051', 'Tokbokki Phô Mai', '치즈 떡볶이', 25000, 8, 'MenuItem_M00051.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00070', 'Khoai Tây Chiên', '감자 튀김', 32000, 9, 'MenuItem_M00070.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00128', 'Gà Viên Chiên Giòn (6 viên)', 'Gà Viên Chiên Giòn (6 viên)', 32000, 9, 'MenuItem_M00128.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00076', 'Phô Mai Que', '모짜렐라 스틱', 39000, 9, 'MenuItem_M00076.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00072', 'Rong Biển Cuộn Fillet Cá Chiên', '어묵김말이 튀김', 39000, 9, 'MenuItem_M00072.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00073', 'Phô Mai Viên', '치즈볼', 29000, 9, 'MenuItem_M00073.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00135', 'Combo khai vị phô mai', 'Phô mai que, phô mai viên, viên thanh cua phô mai', 49000, 9, 'MenuItem_M00135.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00134', 'Kimbap Sasin', '12 cuộn', 59000, 9, 'MenuItem_M00134.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00133', 'Kimbap Sasin', '6 cuộn', 35000, 9, 'MenuItem_M00133.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00069', 'Kimbap Chiên', '바삭한 김밥튀김', 45000, 9, 'MenuItem_M00069.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00071', 'Mandu Chiên Xốt Cay', '칠리 소스를 곁들인 튀김 만두', 35000, 9, 'MenuItem_M00071.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00074', 'Bánh Bạch Tuộc', '타코야키', 39000, 9, 'MenuItem_M00074.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00127', 'Chân Gà Xốt Hàn', 'Chân Gà Xốt Hàn', 49000, 9, 'MenuItem_M00127.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00079', 'Sụn Gà Bắp Chiên Giòn', '버삭한 옥수수 닭 오돌뼈', 45000, 9, 'MenuItem_M00079.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00078', 'Đùi Gà Giòn', '닭 다리 후라이드', 39000, 9, 'MenuItem_M00078.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00080', 'Viên Thanh Cua Phô Mai', '크랩스틱 치즈볼', 45000, 9, 'MenuItem_M00080.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00075', 'Xiên Bánh Cá Hầm', '어묵', 42000, 9, 'MenuItem_M00075.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00077', 'Salad Xốt Mè Rang', '+ Gà Fillet 12.000 VNĐ', 35000, 9, 'MenuItem_M00077.webp', 1, 0, 2, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00085', 'Nước Gạo Hàn Quốc', '달콤한 쌀 음료', 35000, 10, 'MenuItem_M00085.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00097', 'Nước Gạo Hoa Anh Đào', '사쿠라 찹쌀 음료', 35000, 10, 'MenuItem_M00097.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00082', 'Soda Dâu Dưa Lưới', '딸기 메론 소다', 35000, 10, 'MenuItem_M00082.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00083', 'Soda Dừa Dứa Đác Thơm', '파인애플 코코넛 소다와 사탕야자 씨앗', 35000, 10, 'MenuItem_M00083.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00084', 'Soda Thơm Lừng', '멜론 파인애플 소다', 35000, 10, 'MenuItem_M00084.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00115', 'Sting', 'Sting lon', 29000, 10, 'MenuItem_M00115.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00087', 'Trà Dâu Đào', '딸기 히비스커스 홍차', 29000, 10, 'MenuItem_M00087.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00086', 'Trà Đào Sasin', '복숭아 홍차', 29000, 10, 'MenuItem_M00086.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00089', 'Trà Sữa Trân Châu Sasin', '밀크 티', 29000, 10, 'MenuItem_M00089.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00088', 'Trà Sữa Matcha Trân Châu Sasin', '말차 밀크티', 29000, 10, 'MenuItem_M00088.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00104', 'Sprite Size R', 'Sprite size R', 23000, 10, 'MenuItem_M00104.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00102', 'Coca Cola Size R', 'Coca Cola Size R', 23000, 10, 'MenuItem_M00102.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00105', 'Sprite Size L', 'Sprite size L', 27000, 10, 'MenuItem_M00105.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00103', 'Coca Cola Size L', 'Coca cola size L', 27000, 10, 'MenuItem_M00103.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00106', 'Coca Cola', 'Coca cola', 29000, 10, 'MenuItem_M00106.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00107', 'Sprite', 'Sprite', 29000, 10, 'MenuItem_M00107.webp', 1, 0, 0, NOW());
INSERT INTO SanPham (MaSPCode, TenSP, MoTa, DonGia, MaDM, HinhAnh, TrangThai, NoiBat, CapDoCay, NgayTao) VALUES ('M00108', 'Samurai Dâu', 'Samurai dâu', 29000, 10, 'MenuItem_M00108.webp', 1, 0, 0, NOW());



-- Bật lại kiểm tra foreign key
SET FOREIGN_KEY_CHECKS = 1;

SELECT CONCAT('Đã import ', COUNT(*), ' sản phẩm!') AS Result FROM SanPham;
